### ISSUE TITLE
issue Communication

### ISSUE THREAD

**Issue by muwoo** [monkeyWangs/doubanMovie-SSR#1]
服务端渲染相关技术讨论，可以在这里探讨

**Comment by zhouchangshun** [comment]
过来给你点个赞哈，服务器端渲染在首屏渲染速度和SEO上感觉效果很明显嘛，个人感觉这个资料比较少，学习成本不低呀

**Comment by wwb568109135** [comment]
@zhouchangshun 

现在出了中文文档了，比之前成本又低了不少了！
